services:
  # Development container for running Go commands
  go-dev:
    image: golang:1.23-alpine
    build:
      context: .
    working_dir: /app
    volumes:
      - .:/app
      - ./crt:/crt
    tty: true
    ports:
      - "8080:8080"
    environment:
      - CGO_ENABLED=0
      - PORT=8080